services:
  - type: web
    name: vitivinicultura-api
    env: python
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: API_ENV
        value: production
      - key: DEBUG
        value: false
    healthCheckPath: /health 