services:
  - type: web
    name: vitivinicultura-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: API_ENV
        value: production
      - key: DEBUG
        value: false
      # [DEPLOY] 03/06/2025 - MongoDB Atlas Configuration
      - key: MONGODB_URL
        value: mongodb+srv://ederray:eder12345@database.2i6pa4j.mongodb.net/?retryWrites=true&w=majority&appName=Database
      # [DEPLOY] 03/06/2025 - JWT Configuration
      - key: JWT_SECRET_KEY
        value: vitivinicultura-api-secret-key-render-2025
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 60
      # [SECURITY] 03/06/2025 - Redis configurado no painel do Render
      # As credenciais Redis são configuradas diretamente no painel do Render por segurança
    healthCheckPath: /health 