services:
  - type: web
    name: vitivinicultura-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: API_ENV
        value: production
      - key: DEBUG
        value: false
    healthCheckPath: /health 