services:
  - type: web
    name: vitivinicultura-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: API_ENV
        value: production
      - key: DEBUG
        value: false
      # [DEPLOY] 03/06/2025 - MongoDB Atlas Configuration
      - key: MONGODB_URL
        value: mongodb+srv://projeto5mlet:projetofiap@apiembrapa.wcmp3fv.mongodb.net/?retryWrites=true&w=majority&appName=apiEmbrapa
      # [DEPLOY] 03/06/2025 - JWT Configuration
      - key: JWT_SECRET_KEY
        value: vitivinicultura-api-secret-key-render-2025
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 60
    healthCheckPath: /health 